export const FORM_UNIFIED_VARIANT = {
  TEXT: "TEXT",
  NUMBER: "NUMBER",
  TEXTAREA: "TEXTAREA",
  CHECKBOX: "CHECKBOX",
  RADIO_GROUP: "RADIO_GROUP",
  SELECT: "SELECT",
  SELECT_INFINITE: "SELECT_INFINITE",
  UID: "UID",
  RICH_TEXT: "RICH_TEXT",
  DATE_PICKER: "DATE_PICKER",
} as const
